### ISSUE TITLE
Sup.exit()

### ISSUE THREAD

**Issue by anatagawa** [superpowers/superpowers-core#144]
`Sup.exit()` does not work with Electron version greater than v0.37.8

An error appears after you export the game, and used with Electron:
`Uncaught Error: Cannot find module 'remote'`

**Comment by elisee** [comment]
Thanks for the report. This is a bug in Superpowers Game so I opened an issue there: https://github.com/superpowers/superpowers-game/issues/118
